from index import index
from login import login
from signup import signup
from logout import logout
from data import data
from donate import donate
from sponsors import sponsors
from profile import profile
from subteams import subteams
from subteams import description