from index import index
from login import login
from signup import signup
from data import data
from subteams import subteams
from donate import donate
from sponsors import sponsors
from chassis import chassis
from drivetrain import drivetrain
from suspension import suspension
from electrical import electrical