subteam_titles = {
	'chassis'	: 'Chassis',
	'drivetrain': 'Drivetrain',
	'electrical': 'Electrical',
	'suspension': 'Suspension'
}

subteam_descriptions = {
	'chassis'	: 'Body Subteam is in charge of the chassis, stylistic elements, and all ways in which drivers engage with the vehicle\'s interface. Goals for this year include modifying the chassis design to be more robust, improving the driver experience, and making the car look generally more pleasing to the eye.\n As the chassis is being remade this year, there has been a lot of opportunity for improvement and rethinking of design directed toward making the chassis more robust and easier to manufacture. Examples include turning welded joints into bent tubing and implementing a \'whisker\' bumper that covers the entire front of the car. The main elements of the user interface we deal with include the pedals, seat, and body panels, which are all being redesigned to be either more comfortable for the driver or more attractive.\n We conduct FEA (Finite Element Analysis) to simulate different types of collisions on different designs to ensure a sturdy chassis design, make sketch models to simulate how people will interact with the car, and use a variety of techniques and machines for fabrication of our parts, including a water jet cutter and a CNC router to make foam molds for our composites layups.',
	'drivetrain': 'Drivetrain Subteam is responsible for everything from the output of the engine to the input to the wheels and our job is to manage the transfer of power from the engine to the wheels. Beginning with the performance specifications the team would like to have on a given car, we design and select drivetrain components that will enable the car to perform at the desired specifications. This may involve vendor parts or parts we design and fabricate ourselves.\n Currently, we use a team-designed 2-stage reduction chain drive housed in billet aluminium machined in-house at Olin College. This year, we plan to focus on conducting detailed research studies on key parts of the drivetrain and examine the design decisions that we made. We also plan on making changes to parts where we found areas to improve over the course of the past year. All this is in an effort to continuously improve upon efficiency and performance of the drivetrain for years to come.',
	'electrical': 'Electrical subteam is just two years old. We do everything from wiring the brake lights to getting feedback to the driver. We haven\'t encountered any other SAE Baja teams pushing the boundaries of what an electrical subteam could do, and we\'re excited to find out.\nThis year, we\'re equipping the car with a speedometer, tachometer, and a dashboard that will give drivers information such as speed, race stats, and gas level. We are also working on a driver communications system that would let the driver talk to the pit captain during races.',
	'suspension': 'Suspension makes sure that the car handles as well as it possibly can. Through optimizing the roll axis, camber, and other parameters, we make sure that the car performs optimally on all kinds of terrain for all drivers, not just on asphalt for 150-lb drivers. Despite being one of the longest cars at the competition (56 inch track length), Olin has one of the smallest turning radii at 7 feet.\nThis year, we want to further reduce our bump steer, further tune our shocks for optimal performance across the entire camber curve, and update our adjustable shock mount design: an Olin original idea that allows us to even out the handling characteristics for drivers of all weights.'
}